namespace Broker.Mvu.Testing

(* SYNTHETIC FIXTURE: representative Model values, not derived from a
   live BAR session. Real-game evidence regenerated by Story 3 walkthrough —
   see specs/001-tui-grpc-broker/readiness/. *)

open System
open Broker.Core
open Broker.Mvu

module Fixtures =

    let private brokerInfo (startedAt: DateTimeOffset) : Session.BrokerInfo = {
        version = Version(1, 0)
        listenAddress = "127.0.0.1:5021"
        startedAt = startedAt
    }

    let private mkRpcContext (op: string) (i: int64) : Msg.RpcContext = {
        rpcId = Cmd.RpcId i
        receivedAt = DateTimeOffset(2026, 4, 28, 12, 0, 0, TimeSpan.Zero)
        operation = op
    }

    let private synthSnapshot (sessionId: Guid) (tick: int64) (clientCount: int) (unitsPerFrame: int) : Snapshot.GameStateSnapshot =
        let players : Snapshot.PlayerTelemetry list =
            [ for i in 0 .. clientCount - 1 ->
                { playerId = i
                  teamId = i % 2
                  name = sprintf "Player%d" i
                  resources = { metal = 1000.0 + float (i * 100); energy = 800.0 + float (i * 50) }
                  unitCount = unitsPerFrame / max 1 clientCount
                  buildingCount = 5
                  unitClassBreakdown = Map.empty
                  economy =
                    { income = { metal = 12.0; energy = 18.0 }
                      expenditure = { metal = 8.0; energy = 14.0 } }
                  kills = i * 2
                  losses = i } ]
        let units : Snapshot.Unit list =
            [ for i in 0 .. unitsPerFrame - 1 ->
                { id = uint32 i
                  classId = "armcom"
                  ownerPlayerId = i % (max 1 clientCount)
                  pos = { x = float32 (i % 100); y = float32 (i / 100) } } ]
        { sessionId = sessionId
          tick = tick
          capturedAt = DateTimeOffset(2026, 4, 28, 12, 0, 0, TimeSpan.Zero).AddMilliseconds(float tick * 33.0)
          players = players
          units = units
          buildings = []
          features = []
          mapMeta = None }

    let syntheticIdleModel (startedAt: DateTimeOffset) : Model.Model =
        Model.init (brokerInfo startedAt) Model.defaultConfig startedAt

    let syntheticGuestModel (clientCount: int) (tick: int64) : Model.Model =
        let startedAt = DateTimeOffset(2026, 4, 28, 11, 0, 0, TimeSpan.Zero)
        let baseModel = syntheticIdleModel startedAt
        // Attach coordinator (guest mode auto-detected).
        let link : Session.ProxyAiLink =
            { attachedAt = startedAt.AddSeconds 10.0
              protocolVersion = Version(1, 0)
              lastSnapshotAt = Some (DateTimeOffset(2026, 4, 28, 12, 0, 0, TimeSpan.Zero))
              keepAliveIntervalMs = 2500
              pluginId = "highbar-ai-7"
              schemaVersion = "1.0.0"
              engineSha256 = "abc123"
              lastHeartbeatAt = startedAt.AddSeconds 30.0
              lastSeq = uint64 tick }
        // Add scripting clients.
        let mutable roster = ScriptingRoster.empty
        let mutable queues = Map.empty<ScriptingClientId, Model.QueueObservation>
        for i in 1 .. clientCount do
            let id = ScriptingClientId (sprintf "client-%d" i)
            match ScriptingRoster.tryAdd id (Version(1, 0)) startedAt roster with
            | Result.Ok r -> roster <- r
            | _ -> ()
            queues <- Map.add id
                { depth = 0
                  highWaterMark = 0
                  overflowCount = 0
                  lastSampledAt = startedAt
                  lastOverflowAt = None }
                queues
        let snap = synthSnapshot (Guid.NewGuid()) tick clientCount (clientCount * 50)
        { baseModel with
            mode = Mode.Guest
            coordinator = Some link
            roster = roster
            queues = queues
            snapshot = Some snap }

    let syntheticHostModelElevated (elevatedClient: ScriptingClientId) : Model.Model =
        let startedAt = DateTimeOffset(2026, 4, 28, 11, 0, 0, TimeSpan.Zero)
        let baseModel = syntheticIdleModel startedAt
        let lobby : Lobby.LobbyConfig =
            { mapName = "Tabula"
              gameMode = "Skirmish"
              participants =
                [ { slotIndex = 0; kind = ParticipantSlot.ProxyAi; team = 0; boundClient = Some elevatedClient }
                  { slotIndex = 1; kind = ParticipantSlot.BuiltInAi 5; team = 1; boundClient = None } ]
              display = Lobby.Headless }
        let session = Session.newHostSession lobby (startedAt.AddSeconds 5.0)
        let mutable roster = ScriptingRoster.empty
        match ScriptingRoster.tryAdd elevatedClient (Version(1, 0)) startedAt roster with
        | Result.Ok r -> roster <- r
        | _ -> ()
        match ScriptingRoster.grantAdmin elevatedClient roster with
        | Result.Ok r -> roster <- r
        | _ -> ()
        { baseModel with
            mode = Mode.Hosting lobby
            session = Some session
            slots = lobby.participants
            roster = roster
            elevation = Some elevatedClient }

    // ────────────────────────────────────────────────────────────────────
    // Carve-out Msg sequences
    // ────────────────────────────────────────────────────────────────────

    let syntheticT029MsgSequence () : Msg.Msg list =
        // T029: broker–proxy end-to-end transcript. Single coordinator
        // attaches via Heartbeat, opens PushState, ships 10 snapshots,
        // then closes the stream. Carve-out closure: assert that each
        // step lands a coherent Model + audit.
        let baseAt = DateTimeOffset(2026, 4, 28, 12, 0, 0, TimeSpan.Zero)
        let sessionId = Guid.NewGuid()
        let tickAt n = baseAt.AddMilliseconds(float n * 33.0)
        let snapshots =
            [ for i in 1 .. 10 ->
                let snap = synthSnapshot sessionId (int64 i) 0 4
                let snap' = { snap with capturedAt = tickAt i }
                Msg.CoordinatorInbound (Msg.PushStateSnapshot (uint64 i, snap')) ]
        [ Msg.CoordinatorInbound (Msg.Heartbeat ("highbar-ai-7", "1.0.0", "engine-sha", mkRpcContext "Heartbeat" 1L))
          Msg.CoordinatorInbound (Msg.PushStateOpened ("highbar-ai-7", mkRpcContext "PushState" 2L))
          yield! snapshots
          Msg.CoordinatorInbound (Msg.PushStateClosed "stream-end") ]

    let syntheticT037MsgSequence () : Msg.Msg list =
        // T037: host-mode admin walkthrough. Operator opens lobby,
        // launches host session, receives a scripting client, elevates
        // them, dispatches an Admin.Pause command.
        let id1 = ScriptingClientId "client-1"
        let lobbyKey = ConsoleKeyInfo('L', ConsoleKey.L, false, false, false)
        let enterKey = ConsoleKeyInfo('\r', ConsoleKey.Enter, false, false, false)
        let aKey = ConsoleKeyInfo('A', ConsoleKey.A, false, false, false)
        [ Msg.TuiInput (Msg.Keypress lobbyKey)
          Msg.TuiInput (Msg.Keypress enterKey)
          Msg.ScriptingInbound (Msg.Hello (id1, Version(1, 0), mkRpcContext "Hello" 10L))
          Msg.TuiInput (Msg.Keypress aKey)
          Msg.ScriptingInbound (
            Msg.Command (id1,
                { commandId = Guid.NewGuid()
                  originatingClient = id1
                  targetSlot = None
                  kind = CommandPipeline.Admin (CommandPipeline.AdminPayload.Pause)
                  submittedAt = DateTimeOffset(2026, 4, 28, 12, 0, 5, TimeSpan.Zero) })) ]

    let syntheticT042MsgSequence (clientCount: int) (snapshotCount: int) (unitsPerFrame: int) : Msg.Msg list =
        // T042: dashboard under load. clientCount subscribed clients,
        // snapshotCount snapshots each carrying unitsPerFrame units.
        let baseAt = DateTimeOffset(2026, 4, 28, 12, 0, 0, TimeSpan.Zero)
        let sessionId = Guid.NewGuid()
        let helloMsgs =
            [ for i in 1 .. clientCount ->
                let id = ScriptingClientId (sprintf "client-%d" i)
                Msg.ScriptingInbound (Msg.Hello (id, Version(1, 0), mkRpcContext "Hello" (int64 i))) ]
        let subscribeMsgs =
            [ for i in 1 .. clientCount ->
                let id = ScriptingClientId (sprintf "client-%d" i)
                Msg.ScriptingInbound (Msg.Subscribe (id, mkRpcContext "Subscribe" (int64 (100 + i)))) ]
        let attach =
            Msg.CoordinatorInbound (Msg.Heartbeat ("highbar-ai-7", "1.0.0", "engine-sha", mkRpcContext "Heartbeat" 1000L))
        let snapshots =
            [ for i in 1 .. snapshotCount ->
                let snap = synthSnapshot sessionId (int64 i) clientCount unitsPerFrame
                let snap' = { snap with capturedAt = baseAt.AddMilliseconds(float i * 33.0) }
                Msg.CoordinatorInbound (Msg.PushStateSnapshot (uint64 i, snap')) ]
        attach :: helloMsgs @ subscribeMsgs @ snapshots

    let syntheticT046MsgSequence (vizEnabled: bool) : Msg.Msg list =
        // T046: viz toggle and status line. If vizEnabled, the V hotkey
        // turns on viz; otherwise it's a silent no-op (viz is Disabled).
        let vKey = ConsoleKeyInfo('V', ConsoleKey.V, false, false, false)
        let baseSeq =
            [ Msg.TuiInput (Msg.Keypress vKey)
              Msg.CoordinatorInbound (Msg.Heartbeat ("highbar-ai-7", "1.0.0", "engine-sha", mkRpcContext "Heartbeat" 1L))
              Msg.CoordinatorInbound (Msg.PushStateSnapshot (1UL, synthSnapshot (Guid.NewGuid()) 1L 1 4)) ]
        ignore vizEnabled  // toggling is meaningful only when Model.config.vizEnabled = true
        baseSeq
