namespace Broker.Mvu.Testing

(* SYNTHETIC FIXTURE: representative Model values, not derived from a
   live BAR session. Real-game evidence regenerated by Story 3 walkthrough —
   see specs/001-tui-grpc-broker/readiness/. *)

open System
open Broker.Core
open Broker.Mvu

module Fixtures =

    /// Idle-mode `Model` with no coordinator attached.
    val syntheticIdleModel : startedAt:DateTimeOffset -> Model.Model

    /// Guest-mode `Model` with N subscribed scripting clients, mid-game.
    val syntheticGuestModel : clientCount:int -> tick:int64 -> Model.Model

    /// Host-mode `Model` with an elevated client.
    val syntheticHostModelElevated : elevatedClient:ScriptingClientId -> Model.Model

    /// Sequence builders for the carve-out scenarios.
    val syntheticT029MsgSequence : unit -> Msg.Msg list
    val syntheticT037MsgSequence : unit -> Msg.Msg list
    val syntheticT042MsgSequence : clientCount:int -> snapshotCount:int -> unitsPerFrame:int -> Msg.Msg list
    val syntheticT046MsgSequence : vizEnabled:bool -> Msg.Msg list
